name: Build CleanSuite

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-15

    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_16.4.app

      - name: Build CleanSuite App
        run: |
          swift build --configuration release
      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: nightly
          name: Nightly Auto Build
          files: build/Build/Products/Release/CleanSuite.app
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
